### ISSUE TITLE
Postgres connector build failure

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-database-connectors#65]
```
$ ./gradlew build                                                                             [15:35:47]

> Task :egeria-connector-postgres:compileJava
/Users/jonesn/IdeaProjects/egeria-database-connectors/egeria-connector-postgres/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/mapper/PostgresMapper.java:55: error: cannot find symbol
        schemaProps.setOwner(sch.getSchema_owner());
                   ^
  symbol:   method setOwner(String)
  location: variable schemaProps of type DatabaseSchemaProperties
1 error

> Task :egeria-connector-postgres:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':egeria-connector-postgres:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
1 actionable task: 1 executed
```

This error has caused issues with attempting to make fixes under #16, where local builds were working, but all PRs were failing. The inconsistency was caused by https://github.com/odpi/egeria-database-connectors/pull/64 due to picking up local ~/.m2 content. We should be referring to authoritative content - and if the builder wishes to override they can do so via gradle directly.

ie the PR failures at https://github.com/odpi/egeria-database-connectors/pulls are genuine, 

The failing code is in PostgresMapper.java :
```
    /**
     * mapping function that reads tables, columns and primmary keys
     * for a schema from Postgres and adds the data to Egeria
     *
     * @param sch     the Postgres database attributes to be
     * @return        the Egeria schema properties
     */
    public static DatabaseSchemaProperties getSchemaProperties(PostgresSchema sch)
    {
        DatabaseSchemaProperties schemaProps = new DatabaseSchemaProperties();
        schemaProps.setDisplayName(sch.getQualifiedName());
        schemaProps.setQualifiedName(sch.getQualifiedName());
        schemaProps.setOwner(sch.getSchema_owner());
        schemaProps.setAdditionalProperties(sch.getProperties());

        return schemaProps;
    }
```

DatabaseSchemaProperties no longer has a setOwner method

This has probably changed recently in egeria, in a very recent code change
cc: @wbittles @mandy-chessell

**Comment by planetf1** [comment]
https://github.com/odpi/egeria-database-connectors/pull/67 is open as an example (and to prove build failure cause), which
will no longer call setOwner on DatabaseSchemaProperties. 

All properties are already added to extendedProperties via setAdditionalProperties in any case

Is this sufficient for now?

**Comment by planetf1** [comment]
Last change in this area was 630d400f95c3af414b0dd5a6c647a525f50e0102 ?

**Comment by planetf1** [comment]
confirmed as expected behaviour - fields were deliberately removed as they could not be filled in properly.
